CREATE TABLE spring_boot_practice.person (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        full_name varchar(100) NOT NULL UNIQUE,
                        year_of_birth int NOT NULL
);

CREATE TABLE spring_boot_practice.book (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title varchar(100) NOT NULL,
                      author varchar(100) NOT NULL,
                      year int NOT NULL,
                      person_id int REFERENCES spring_boot_practice.person(id) ON DELETE SET NULL
);